services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gps_tracker_front_v2_app
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=gps_tracker_dev
      - DB_USERNAME=root
      - DB_PASSWORD=root

  web:
    image: nginx:alpine
    container_name: nginx
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8082:80"
    networks:
      - laravel
    depends_on:
      - app
    platform: linux/amd64  # Ensures compatibility with arm64

  mysql:
    image: mysql:8.0
    container_name: gps-tracker-front-v2-mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Change the host port to 3307 to avoid conflicts
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: gps-tracker-front-v2-pma
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8083:80"
    depends_on:
      - mysql
    networks:
      - laravel
    platform: linux/amd64  # Ensures compatibility with arm64

networks:
  laravel:

volumes:
  mysql_data:
